subdir = src/gausskernel/storage/access/heap/proto
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

OBJS = message.pb.o client.pb.o node.pb.o server.pb.o storage.pb.o transaction.pb.o

include $(top_srcdir)/src/gausskernel/common.mk
